/*
 * GENERATED by scripts/analyze-media.mjs — do not edit this file by hand.
 * Every path here was decided by looking at the photograph and written down in scripts/media-overrides.json.
 * To change one, edit that file and run `node scripts/analyze-media.mjs` again.
 * 62 live files, generated 2026-09-29.
 */

export type MediaEntry = {
  src: string;
  alt: string;
  title: string;
  category: string;
  tags: string[];
  width: number | null;
  height: number | null;
};

export const MEDIA: Record<string, MediaEntry[]> = {
  "room_standard": [
    {
      "src": "/media/organized/room_standard/691294046.jpg",
      "alt": "A standard room at Sunrise Motel: the double bed with its wardrobe and armchair on polished wooden floors",
      "title": "The Standard — standard room at Sunrise Motel",
      "category": "room_standard",
      "tags": [
        "bed",
        "double",
        "armchair",
        "wardrobe",
        "wooden-floor",
        "standard"
      ],
      "width": 1024,
      "height": 683
    },
    {
      "src": "/media/organized/room_standard/twin-main.jpg",
      "alt": "The twin room at Sunrise Motel: two single beds on polished wooden floors beside the window",
      "title": "The Twin — twin room at Sunrise Motel",
      "category": "room_standard",
      "tags": [
        "bed",
        "single",
        "twin",
        "two-beds",
        "wooden-floor",
        "en-suite"
      ],
      "width": 960,
      "height": 640
    },
    {
      "src": "/media/organized/room_standard/deluxe-room.jpg",
      "alt": "The twin room at Sunrise Motel with two single beds under mosquito nets and a private bathroom",
      "title": "The Twin — twin room at Sunrise Motel with two single beds u...",
      "category": "room_standard",
      "tags": [
        "bed",
        "single",
        "twin",
        "two-beds",
        "mosquito-net",
        "en-suite"
      ],
      "width": 960,
      "height": 640
    },
    {
      "src": "/media/organized/room_standard/room-layout.jpg",
      "alt": "A room at Sunrise Motel, showing the layout of the beds and furniture",
      "title": "The Standard — room at Sunrise Motel",
      "category": "room_standard",
      "tags": [
        "room",
        "layout",
        "review"
      ],
      "width": 640,
      "height": 640
    },
    {
      "src": "/media/organized/room_standard/twin-setup.jpg",
      "alt": "The twin room at Sunrise Motel with its two beds made up",
      "title": "The Twin — twin room at Sunrise Motel with its two beds made up",
      "category": "room_standard",
      "tags": [
        "bed",
        "twin",
        "review"
      ],
      "width": 960,
      "height": 480
    },
    {
      "src": "/media/organized/room_standard/691295644.jpg",
      "alt": "The twin room at Sunrise Motel: two single beds with mosquito nets and a private bathroom door",
      "title": "The Twin — twin room at Sunrise Motel",
      "category": "room_standard",
      "tags": [
        "bed",
        "single",
        "twin",
        "two-beds",
        "en-suite",
        "mosquito-net"
      ],
      "width": 1024,
      "height": 683
    },
    {
      "src": "/media/organized/room_standard/691296171.jpg",
      "alt": "A twin room at Sunrise Motel with two single beds on the polished wooden floor by the window",
      "title": "The Twin — twin room at Sunrise Motel with two single beds o...",
      "category": "room_standard",
      "tags": [
        "bed",
        "single",
        "twin",
        "two-beds",
        "wooden-floor",
        "window"
      ],
      "width": 1024,
      "height": 683
    }
  ],
  "room_deluxe": [
    {
      "src": "/media/organized/room_deluxe/listing-12.jpg",
      "alt": "The four-poster double bed in a Sunrise Motel deluxe room, with the mosquito net drawn back",
      "title": "The Deluxe — four-poster double bed in a Sunrise Motel deluxe...",
      "category": "room_deluxe",
      "tags": [
        "bed",
        "double",
        "canopy",
        "mosquito-net",
        "wooden-floor",
        "spacious"
      ],
      "width": 960,
      "height": 480
    },
    {
      "src": "/media/organized/room_deluxe/hero-standard.jpg",
      "alt": "A Sunrise Motel room with its four-poster bed under a mosquito net, polished wooden floor and bar fridge",
      "title": "The Deluxe — Sunrise Motel room with its four-poster bed under...",
      "category": "room_deluxe",
      "tags": [
        "bed",
        "double",
        "canopy",
        "mosquito-net",
        "wooden-floor",
        "fridge",
        "en-suite"
      ],
      "width": 960,
      "height": 640
    },
    {
      "src": "/media/organized/room_deluxe/twin-view.jpg",
      "alt": "The four-poster double bed with its mosquito net in a Sunrise Motel deluxe room, seen across the wooden floor",
      "title": "The Deluxe — four-poster double bed with its mosquito net in a...",
      "category": "room_deluxe",
      "tags": [
        "bed",
        "double",
        "canopy",
        "mosquito-net",
        "wooden-floor"
      ],
      "width": 960,
      "height": 480
    },
    {
      "src": "/media/organized/room_deluxe/520596171.jpg",
      "alt": "The four-poster double bed with its mosquito net in a Sunrise Motel deluxe room, wooden floors underfoot",
      "title": "The Deluxe — four-poster double bed with its mosquito net in a...",
      "category": "room_deluxe",
      "tags": [
        "bed",
        "double",
        "canopy",
        "mosquito-net",
        "wooden-floor",
        "spacious"
      ],
      "width": 1024,
      "height": 512
    },
    {
      "src": "/media/organized/room_deluxe/691294368.jpg",
      "alt": "A deluxe room at Sunrise Motel with its four-poster bed, bar fridge and en-suite doorway",
      "title": "The Deluxe — deluxe room at Sunrise Motel with its four-poster...",
      "category": "room_deluxe",
      "tags": [
        "bed",
        "canopy",
        "fridge",
        "en-suite",
        "mosquito-net",
        "bar-fridge"
      ],
      "width": 1024,
      "height": 683
    }
  ],
  "room_family": [
    {
      "src": "/media/organized/room_family/691294883.jpg",
      "alt": "A family room at Sunrise Motel: the double bed with extra single beds, a desk and a bar fridge",
      "title": "Family room at Sunrise Motel",
      "category": "room_family",
      "tags": [
        "bed",
        "double",
        "single",
        "family",
        "fridge",
        "desk",
        "mosquito-net"
      ],
      "width": 1024,
      "height": 683
    }
  ],
  "building_exterior": [
    {
      "src": "/media/organized/building_exterior/cute-and-cozy-place-friendly.jpg",
      "alt": "The Sunrise Motel facade and its arched sign, with potted plants along the veranda",
      "title": "Sunrise Motel facade and its arched sign",
      "category": "building_exterior",
      "tags": [
        "exterior",
        "sign",
        "facade",
        "day",
        "plants"
      ],
      "width": 1400,
      "height": 800
    },
    {
      "src": "/media/organized/building_exterior/deluxe-main.jpg",
      "alt": "The Sun Rise Motel facade and its round sign above the veranda, potted plants along the front",
      "title": "Sun Rise Motel facade and its round sign above th...",
      "category": "building_exterior",
      "tags": [
        "exterior",
        "sign",
        "facade",
        "veranda",
        "plants"
      ],
      "width": 960,
      "height": 480
    },
    {
      "src": "/media/organized/building_exterior/520576165.jpg",
      "alt": "The Sunrise Motel entrance arch and veranda, ringed with potted plants",
      "title": "Sunrise Motel entrance arch and veranda",
      "category": "building_exterior",
      "tags": [
        "exterior",
        "sign",
        "facade",
        "plants",
        "veranda"
      ],
      "width": 1024,
      "height": 512
    },
    {
      "src": "/media/organized/building_exterior/520576130.jpg",
      "alt": "The Sun Rise Motel facade with its round sign and the shaded veranda where guests wait",
      "title": "Sun Rise Motel facade with its round sign and the...",
      "category": "building_exterior",
      "tags": [
        "exterior",
        "sign",
        "facade",
        "veranda",
        "aircon"
      ],
      "width": 1024,
      "height": 512
    },
    {
      "src": "/media/organized/building_exterior/520576061.jpg",
      "alt": "The Sunrise Motel gate and front lawn at dusk, with the paved forecourt in front of the building",
      "title": "Sunrise Motel gate and front lawn at dusk",
      "category": "building_exterior",
      "tags": [
        "exterior",
        "gate",
        "garden",
        "forecourt",
        "evening",
        "entrance"
      ],
      "width": 1024,
      "height": 512
    },
    {
      "src": "/media/organized/building_exterior/cute-and-cozy-place-friendly-4.jpg",
      "alt": "The Sunrise Motel frontage and its round sign seen from the forecourt",
      "title": "Sunrise Motel frontage and its round sign seen fr...",
      "category": "building_exterior",
      "tags": [
        "exterior",
        "sign",
        "facade",
        "day",
        "plants",
        "near-duplicate"
      ],
      "width": 1400,
      "height": 1050
    }
  ],
  "building_interior": [
    {
      "src": "/media/organized/building_interior/cute-and-cozy-place-friendly-3.jpg",
      "alt": "The wooden staircase up from the Sunrise Motel lobby, hung with local artwork",
      "title": "Wooden staircase up from the Sunrise Motel lobby",
      "category": "building_interior",
      "tags": [
        "staircase",
        "lobby",
        "wooden",
        "interior",
        "art"
      ],
      "width": 1100,
      "height": 1467
    },
    {
      "src": "/media/organized/building_interior/lobby-lights.jpg",
      "alt": "The Sunrise Motel lounge in the evening, warm hanging lights over the low table",
      "title": "Sunrise Motel lounge in the evening",
      "category": "building_interior",
      "tags": [
        "lounge",
        "lobby",
        "evening",
        "lights",
        "interior"
      ],
      "width": 1000,
      "height": 667
    },
    {
      "src": "/media/organized/building_interior/connect-coffee-snacks.jpg",
      "alt": "Sunrise Motel's own board by reception: fuel up with Sunrise coffee, stay connected with fast Starlink internet, try our coffee and snacks",
      "title": "Sunrise Motel's own board by reception",
      "category": "building_interior",
      "tags": [
        "board",
        "poster",
        "coffee",
        "starlink",
        "reception",
        "own-words"
      ],
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/media/organized/building_interior/bathroom.jpg",
      "alt": "The private bathroom in a room at Sunrise Motel, with hot water on demand",
      "title": "Private bathroom in a room at Sunrise Motel",
      "category": "building_interior",
      "tags": [
        "bathroom",
        "en-suite",
        "shower",
        "review",
        "room-facility"
      ],
      "width": 960,
      "height": 640
    }
  ],
  "reception": [
    {
      "src": "/media/organized/reception/reception.jpg",
      "alt": "The welcome desk at Sunrise Motel, lit and staffed for arrivals",
      "title": "Welcome desk at Sunrise Motel",
      "category": "reception",
      "tags": [
        "reception",
        "welcome-desk",
        "staffed",
        "interior",
        "arrivals"
      ],
      "width": 1000,
      "height": 667
    }
  ],
  "restaurant": [
    {
      "src": "/media/organized/restaurant/night-terrace.jpg",
      "alt": "The Sunrise Motel terrace laid for dinner in the evening",
      "title": "Sunrise Motel terrace laid for dinner in the evening",
      "category": "restaurant",
      "tags": [
        "terrace",
        "evening",
        "tables",
        "dining",
        "lights"
      ],
      "width": 1000,
      "height": 667
    },
    {
      "src": "/media/organized/restaurant/garden-dinner.jpg",
      "alt": "Dinner laid out in the garden at Sunrise Motel",
      "title": "Dinner laid out in the garden at Sunrise Motel",
      "category": "restaurant",
      "tags": [
        "garden",
        "dinner",
        "tables",
        "outdoor",
        "dining"
      ],
      "width": 1000,
      "height": 667
    },
    {
      "src": "/media/organized/restaurant/evening-tables.jpg",
      "alt": "Tables set for the evening service at Sunrise Motel",
      "title": "Tables set for the evening service at Sunrise Motel",
      "category": "restaurant",
      "tags": [
        "evening",
        "tables",
        "dining",
        "restaurant"
      ],
      "width": 900,
      "height": 600
    },
    {
      "src": "/media/organized/restaurant/520576108.jpg",
      "alt": "Tables on the covered restaurant terrace at Sunrise Motel, with the carved statue beside the open doors",
      "title": "Tables on the covered restaurant terrace at Sunri...",
      "category": "restaurant",
      "tags": [
        "terrace",
        "tables",
        "open-air",
        "statue",
        "dining",
        "restaurant"
      ],
      "width": 1024,
      "height": 512
    },
    {
      "src": "/media/organized/restaurant/cute-and-cozy-place-friendly-2.jpg",
      "alt": "The covered terrace at Sunrise Motel with its carved statue, thatch roof and guest tables",
      "title": "Covered terrace at Sunrise Motel with its carved...",
      "category": "restaurant",
      "tags": [
        "terrace",
        "statue",
        "thatch",
        "tables",
        "dining"
      ],
      "width": 1100,
      "height": 1467
    },
    {
      "src": "/media/organized/restaurant/520576171.jpg",
      "alt": "The long dining table and chairs in the Sunrise Motel restaurant, lit by the side windows",
      "title": "Long dining table and chairs in the Sunrise Motel...",
      "category": "restaurant",
      "tags": [
        "restaurant",
        "tables",
        "hall",
        "interior",
        "dining"
      ],
      "width": 1024,
      "height": 512
    },
    {
      "src": "/media/organized/restaurant/listing-11.jpg",
      "alt": "A corner of the covered Sunrise Motel terrace under its thatch roof, tables and chairs ready for guests",
      "title": "Corner of the covered Sunrise Motel terrace under...",
      "category": "restaurant",
      "tags": [
        "terrace",
        "thatch",
        "lounge",
        "tables",
        "interior"
      ],
      "width": 960,
      "height": 583
    },
    {
      "src": "/media/organized/restaurant/unwind-braai-chef.jpg",
      "alt": "The braai grill at Sunrise Motel with a chef carrying a plate of grilled meat and onions",
      "title": "Braai grill at Sunrise Motel with a chef carrying...",
      "category": "restaurant",
      "tags": [
        "braai",
        "grill",
        "chef",
        "collage",
        "real-photos",
        "outdoor-cooking",
        "kitchen"
      ],
      "width": 1280,
      "height": 853
    },
    {
      "src": "/media/organized/restaurant/workspace-coffee.jpg",
      "alt": "Coffee and a place to work at Sunrise Motel, with the Starlink Wi-Fi",
      "title": "Coffee and a place to work at Sunrise Motel",
      "category": "restaurant",
      "tags": [
        "coffee",
        "workspace",
        "wifi",
        "laptop",
        "snacks"
      ],
      "width": 1200,
      "height": 1600
    }
  ],
  "food_dish": [
    {
      "src": "/media/organized/food_dish/food-chambo.jpg",
      "alt": "Whole grilled chambo with chips, tomato and onion salad at Sunrise Motel",
      "title": "Whole grilled chambo with chips",
      "category": "food_dish",
      "tags": [
        "food",
        "fish",
        "chambo",
        "chips",
        "grilled",
        "salad"
      ],
      "width": 1600,
      "height": 1200
    },
    {
      "src": "/media/organized/food_dish/dine-mutton-curry.jpg",
      "alt": "Mutton curry with folded chapati and a bowl of dhal at Sunrise Motel",
      "title": "Mutton curry with folded chapati and a bowl of dh...",
      "category": "food_dish",
      "tags": [
        "food",
        "mutton-curry",
        "chapati",
        "dhal",
        "branded",
        "dish",
        "wide"
      ],
      "width": 1944,
      "height": 1296
    },
    {
      "src": "/media/organized/food_dish/food-nsima-beef.jpg",
      "alt": "The filename reads like a plated dish — check the picture before trusting it",
      "title": "food-nsima-beef.jpg",
      "category": "food_dish",
      "tags": [
        "food",
        "dish",
        "landscape"
      ],
      "width": 1408,
      "height": 1408
    },
    {
      "src": "/media/organized/food_dish/food-salad.jpg",
      "alt": "The filename reads like a plated dish — check the picture before trusting it",
      "title": "food-salad.jpg",
      "category": "food_dish",
      "tags": [
        "food",
        "dish",
        "wide"
      ],
      "width": 900,
      "height": 600
    },
    {
      "src": "/media/organized/food_dish/food-curry.jpg",
      "alt": "The filename reads like a plated dish — check the picture before trusting it",
      "title": "food-curry.jpg",
      "category": "food_dish",
      "tags": [
        "food",
        "dish",
        "wide"
      ],
      "width": 900,
      "height": 600
    },
    {
      "src": "/media/organized/food_dish/food-grill.jpg",
      "alt": "The filename reads like a plated dish — check the picture before trusting it",
      "title": "food-grill.jpg",
      "category": "food_dish",
      "tags": [
        "food",
        "dish",
        "wide"
      ],
      "width": 900,
      "height": 600
    },
    {
      "src": "/media/organized/food_dish/dine-roast-beef.jpg",
      "alt": "Sliced roast beef with roast potatoes, as served at Sunrise Motel",
      "title": "Sliced roast beef with roast potatoes",
      "category": "food_dish",
      "tags": [
        "food",
        "roast-beef",
        "potatoes",
        "branded",
        "sunday-lunch",
        "unclassified",
        "wide"
      ],
      "width": 1280,
      "height": 853
    },
    {
      "src": "/media/organized/food_dish/dine-potato-salad.jpg",
      "alt": "Creamy potato salad with egg and green beans at Sunrise Motel",
      "title": "Creamy potato salad with egg and green beans at S...",
      "category": "food_dish",
      "tags": [
        "food",
        "potato-salad",
        "egg",
        "green-beans",
        "branded",
        "dish",
        "wide"
      ],
      "width": 1280,
      "height": 853
    },
    {
      "src": "/media/organized/food_dish/dine-carrot-salad.jpg",
      "alt": "Grated carrot salad with olives and onion, served at Sunrise Motel",
      "title": "Grated carrot salad with olives and onion",
      "category": "food_dish",
      "tags": [
        "food",
        "carrot-salad",
        "olives",
        "branded",
        "side",
        "dish",
        "wide"
      ],
      "width": 1280,
      "height": 853
    },
    {
      "src": "/media/organized/food_dish/dine-boiled-beef.jpg",
      "alt": "Slow-boiled beef in its own broth, as served at Sunrise Motel",
      "title": "Slow-boiled beef in its own broth",
      "category": "food_dish",
      "tags": [
        "food",
        "boiled-beef",
        "broth",
        "branded",
        "unclassified",
        "wide"
      ],
      "width": 1280,
      "height": 853
    }
  ],
  "bar": [
    {
      "src": "/media/organized/bar/happy-hour-terrace.jpg",
      "alt": "The terrace at Sunrise Motel during happy hour, tables out under the evening sky",
      "title": "Terrace at Sunrise Motel during happy hour",
      "category": "bar",
      "tags": [
        "terrace",
        "happy-hour",
        "drinks",
        "outdoor",
        "seating"
      ],
      "width": 1600,
      "height": 1200
    },
    {
      "src": "/media/organized/bar/drinks-poolside.jpg",
      "alt": "Drinks beside the pool table in the Sunrise Motel bar lounge",
      "title": "Drinks beside the pool table in the Sunrise Motel...",
      "category": "bar",
      "tags": [
        "drinks",
        "pool-table",
        "bar",
        "lounge"
      ],
      "width": 900,
      "height": 600
    },
    {
      "src": "/media/organized/bar/520576151.jpg",
      "alt": "The bar at Sunrise Motel: guests at the counter under the SuperSport and Manchester United flags",
      "title": "Bar at Sunrise Motel",
      "category": "bar",
      "tags": [
        "bar",
        "stools",
        "supersport",
        "sport",
        "guests",
        "drinks"
      ],
      "width": 1024,
      "height": 512
    },
    {
      "src": "/media/organized/bar/cute-and-cozy-place-friendly-1.jpg",
      "alt": "Inside the Sunrise Motel bar: the counter, its wooden stools and the big screen over the bottles",
      "title": "Inside the Sunrise Motel bar",
      "category": "bar",
      "tags": [
        "bar",
        "stools",
        "supersport",
        "sport",
        "drinks"
      ],
      "width": 1400,
      "height": 1050
    },
    {
      "src": "/media/organized/bar/deluxe-detail.jpg",
      "alt": "The bar at Sunrise Motel, guests on stools under the SuperSport and Manchester United flags",
      "title": "Bar at Sunrise Motel",
      "category": "bar",
      "tags": [
        "bar",
        "stools",
        "supersport",
        "sport",
        "drinks",
        "guests"
      ],
      "width": 960,
      "height": 480
    },
    {
      "src": "/media/organized/bar/520596180.jpg",
      "alt": "The thatched bar terrace at Sunrise Motel, tables set under the Castel Beer sign",
      "title": "Thatched bar terrace at Sunrise Motel",
      "category": "bar",
      "tags": [
        "bar",
        "thatch",
        "terrace",
        "tables",
        "castel"
      ],
      "width": 1024,
      "height": 512
    }
  ],
  "breakfast": [
    {
      "src": "/media/organized/breakfast/breakfast-full.jpg",
      "alt": "A full breakfast plate at Sunrise Motel",
      "title": "Full breakfast plate at Sunrise Motel",
      "category": "breakfast",
      "tags": [
        "breakfast",
        "full",
        "eggs",
        "plate"
      ],
      "width": 1000,
      "height": 667
    },
    {
      "src": "/media/organized/breakfast/breakfast-plate.jpg",
      "alt": "Breakfast served at Sunrise Motel",
      "title": "Breakfast served at Sunrise Motel",
      "category": "breakfast",
      "tags": [
        "breakfast",
        "plate",
        "eggs",
        "morning"
      ],
      "width": 1000,
      "height": 668
    },
    {
      "src": "/media/organized/breakfast/breakfast-coffee.jpg",
      "alt": "Morning coffee at Sunrise Motel, brewed from Malawian beans",
      "title": "Morning coffee at Sunrise Motel",
      "category": "breakfast",
      "tags": [
        "breakfast",
        "coffee",
        "morning",
        "cup"
      ],
      "width": 900,
      "height": 600
    }
  ],
  "amenity_garden": [
    {
      "src": "/media/organized/amenity_garden/courtyard.jpg",
      "alt": "The open-air courtyard at Sunrise Motel with its garden and seating",
      "title": "Open-air courtyard at Sunrise Motel with its gard...",
      "category": "amenity_garden",
      "tags": [
        "courtyard",
        "garden",
        "open-air",
        "seating"
      ],
      "width": 900,
      "height": 600
    },
    {
      "src": "/media/organized/amenity_garden/braai-lawn.jpg",
      "alt": "The braai lawn in the Sunrise Motel garden",
      "title": "Braai lawn in the Sunrise Motel garden",
      "category": "amenity_garden",
      "tags": [
        "braai",
        "lawn",
        "garden",
        "outdoor",
        "grill"
      ],
      "width": 1600,
      "height": 1200
    },
    {
      "src": "/media/organized/amenity_garden/garden-seating.jpg",
      "alt": "Garden seating in the grounds of Sunrise Motel, tables under the trees",
      "title": "Garden seating in the grounds of Sunrise Motel",
      "category": "amenity_garden",
      "tags": [
        "garden",
        "seating",
        "outdoor",
        "tables"
      ],
      "width": 1000,
      "height": 667
    }
  ],
  "amenity_parking": [
    {
      "src": "/media/organized/amenity_parking/520576120.jpg",
      "alt": "Guest cars parked on the paved drive beside the Sunrise Motel building, under the trees",
      "title": "Guest cars parked on the paved drive beside the S...",
      "category": "amenity_parking",
      "tags": [
        "parking",
        "cars",
        "exterior",
        "brick",
        "secure"
      ],
      "width": 1024,
      "height": 512
    }
  ],
  "event": [
    {
      "src": "/media/organized/event/unwind-happy-hour-board.jpg",
      "alt": "The Sunrise Motel happy hour poster: local beers 20% off every Wednesday",
      "title": "Sunrise Motel happy hour poster",
      "category": "event",
      "tags": [
        "poster",
        "happy-hour",
        "beer",
        "wednesday",
        "braai",
        "board",
        "prices",
        "announcement"
      ],
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/media/organized/event/unwind-happy-hour-ice.jpg",
      "alt": "Sunrise Motel happy hour: beers on ice, every Wednesday from 5pm",
      "title": "Sunrise Motel happy hour",
      "category": "event",
      "tags": [
        "poster",
        "happy-hour",
        "beer",
        "braai",
        "wednesday",
        "drinks",
        "ice",
        "bar"
      ],
      "width": 1080,
      "height": 1080
    },
    {
      "src": "/media/organized/event/match-day.jpg",
      "alt": "Match day at Sunrise Motel, the game on the big screen",
      "title": "Match day at Sunrise Motel",
      "category": "event",
      "tags": [
        "match-day",
        "sport",
        "big-screen",
        "crowd"
      ],
      "width": 1000,
      "height": 667
    },
    {
      "src": "/media/organized/event/unwind-video-poster.jpg",
      "alt": "The big screen at Sunrise Motel showing a live football match",
      "title": "Big screen at Sunrise Motel showing a live footba...",
      "category": "event",
      "tags": [
        "video-poster",
        "match-day",
        "sport",
        "screen",
        "entertainment"
      ],
      "width": 852,
      "height": 478
    }
  ],
  "team_staff": [
    {
      "src": "/media/organized/team_staff/connect-hospitality-team.jpg",
      "alt": "A Sunrise Motel waitress carrying a tray of cold drinks and taking an order",
      "title": "Sunrise Motel waitress carrying a tray of cold dr...",
      "category": "team_staff",
      "tags": [
        "staff",
        "waitress",
        "hospitality",
        "poster",
        "team",
        "service"
      ],
      "width": 695,
      "height": 875
    }
  ]
};

export const ROOM_PHOTOS: Record<string, MediaEntry[]> = {
  "standard": [
    {
      "src": "/media/organized/room_standard/691294046.jpg",
      "alt": "A standard room at Sunrise Motel: the double bed with its wardrobe and armchair on polished wooden floors",
      "title": "The Standard — standard room at Sunrise Motel",
      "category": "room_standard",
      "tags": [
        "bed",
        "double",
        "armchair",
        "wardrobe",
        "wooden-floor",
        "standard"
      ],
      "width": 1024,
      "height": 683
    },
    {
      "src": "/media/organized/room_standard/room-layout.jpg",
      "alt": "A room at Sunrise Motel, showing the layout of the beds and furniture",
      "title": "The Standard — room at Sunrise Motel",
      "category": "room_standard",
      "tags": [
        "room",
        "layout",
        "review"
      ],
      "width": 640,
      "height": 640
    }
  ],
  "deluxe": [
    {
      "src": "/media/organized/room_deluxe/listing-12.jpg",
      "alt": "The four-poster double bed in a Sunrise Motel deluxe room, with the mosquito net drawn back",
      "title": "The Deluxe — four-poster double bed in a Sunrise Motel deluxe...",
      "category": "room_deluxe",
      "tags": [
        "bed",
        "double",
        "canopy",
        "mosquito-net",
        "wooden-floor",
        "spacious"
      ],
      "width": 960,
      "height": 480
    },
    {
      "src": "/media/organized/room_deluxe/hero-standard.jpg",
      "alt": "A Sunrise Motel room with its four-poster bed under a mosquito net, polished wooden floor and bar fridge",
      "title": "The Deluxe — Sunrise Motel room with its four-poster bed under...",
      "category": "room_deluxe",
      "tags": [
        "bed",
        "double",
        "canopy",
        "mosquito-net",
        "wooden-floor",
        "fridge",
        "en-suite"
      ],
      "width": 960,
      "height": 640
    },
    {
      "src": "/media/organized/room_deluxe/twin-view.jpg",
      "alt": "The four-poster double bed with its mosquito net in a Sunrise Motel deluxe room, seen across the wooden floor",
      "title": "The Deluxe — four-poster double bed with its mosquito net in a...",
      "category": "room_deluxe",
      "tags": [
        "bed",
        "double",
        "canopy",
        "mosquito-net",
        "wooden-floor"
      ],
      "width": 960,
      "height": 480
    },
    {
      "src": "/media/organized/room_deluxe/520596171.jpg",
      "alt": "The four-poster double bed with its mosquito net in a Sunrise Motel deluxe room, wooden floors underfoot",
      "title": "The Deluxe — four-poster double bed with its mosquito net in a...",
      "category": "room_deluxe",
      "tags": [
        "bed",
        "double",
        "canopy",
        "mosquito-net",
        "wooden-floor",
        "spacious"
      ],
      "width": 1024,
      "height": 512
    },
    {
      "src": "/media/organized/room_deluxe/691294368.jpg",
      "alt": "A deluxe room at Sunrise Motel with its four-poster bed, bar fridge and en-suite doorway",
      "title": "The Deluxe — deluxe room at Sunrise Motel with its four-poster...",
      "category": "room_deluxe",
      "tags": [
        "bed",
        "canopy",
        "fridge",
        "en-suite",
        "mosquito-net",
        "bar-fridge"
      ],
      "width": 1024,
      "height": 683
    }
  ],
  "twin": [
    {
      "src": "/media/organized/room_standard/twin-main.jpg",
      "alt": "The twin room at Sunrise Motel: two single beds on polished wooden floors beside the window",
      "title": "The Twin — twin room at Sunrise Motel",
      "category": "room_standard",
      "tags": [
        "bed",
        "single",
        "twin",
        "two-beds",
        "wooden-floor",
        "en-suite"
      ],
      "width": 960,
      "height": 640
    },
    {
      "src": "/media/organized/room_standard/deluxe-room.jpg",
      "alt": "The twin room at Sunrise Motel with two single beds under mosquito nets and a private bathroom",
      "title": "The Twin — twin room at Sunrise Motel with two single beds u...",
      "category": "room_standard",
      "tags": [
        "bed",
        "single",
        "twin",
        "two-beds",
        "mosquito-net",
        "en-suite"
      ],
      "width": 960,
      "height": 640
    },
    {
      "src": "/media/organized/room_standard/twin-setup.jpg",
      "alt": "The twin room at Sunrise Motel with its two beds made up",
      "title": "The Twin — twin room at Sunrise Motel with its two beds made up",
      "category": "room_standard",
      "tags": [
        "bed",
        "twin",
        "review"
      ],
      "width": 960,
      "height": 480
    },
    {
      "src": "/media/organized/room_standard/691295644.jpg",
      "alt": "The twin room at Sunrise Motel: two single beds with mosquito nets and a private bathroom door",
      "title": "The Twin — twin room at Sunrise Motel",
      "category": "room_standard",
      "tags": [
        "bed",
        "single",
        "twin",
        "two-beds",
        "en-suite",
        "mosquito-net"
      ],
      "width": 1024,
      "height": 683
    },
    {
      "src": "/media/organized/room_standard/691296171.jpg",
      "alt": "A twin room at Sunrise Motel with two single beds on the polished wooden floor by the window",
      "title": "The Twin — twin room at Sunrise Motel with two single beds o...",
      "category": "room_standard",
      "tags": [
        "bed",
        "single",
        "twin",
        "two-beds",
        "wooden-floor",
        "window"
      ],
      "width": 1024,
      "height": 683
    }
  ]
};

export const HERO_VIDEO: MediaEntry | null = {
  "src": "/media/sunrise-tour-480p.mp4",
  "alt": "A video whose name reads like the property tour, so it is the home page candidate",
  "title": "sunrise-tour-480p.mp4",
  "category": "building_exterior",
  "tags": [
    "hero_video",
    "large"
  ],
  "width": null,
  "height": null
};

export const HERO_IMAGE: MediaEntry | null = {
  "src": "/media/organized/building_exterior/cute-and-cozy-place-friendly.jpg",
  "alt": "The Sunrise Motel facade and its arched sign, with potted plants along the veranda",
  "title": "Sunrise Motel facade and its arched sign",
  "category": "building_exterior",
  "tags": [
    "exterior",
    "sign",
    "facade",
    "day",
    "plants"
  ],
  "width": 1400,
  "height": 800
};

/** The cover of a category — the first live photo, which is the one the run chose. */
export const coverOf = (category: string): MediaEntry | null => MEDIA[category]?.[0] ?? null;

/** The photographs of a room type, cover first; falls back to whatever rooms there are. */
export const photosOf = (roomTypeId: string): MediaEntry[] =>
  ROOM_PHOTOS[roomTypeId] ?? ROOM_PHOTOS.standard ?? ROOM_PHOTOS.deluxe ?? [];
